# Generated by Django 4.2.4 on 2023-09-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedureId', models.AutoField(primary_key=True, serialize=False, verbose_name='procedure id')),
                ('partId', models.CharField(max_length=200, verbose_name='part id')),
                ('description', models.CharField(max_length=600, verbose_name='procedure description')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testID', models.AutoField(primary_key=True, serialize=False, verbose_name='test id')),
                ('docDirectory', models.FilePathField(path='/home/images', verbose_name='document directory')),
                ('partId', models.CharField(max_length=200, verbose_name='part id')),
                ('testDescription', models.CharField(max_length=600, verbose_name='test description')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('outputId', models.AutoField(primary_key=True, serialize=False, verbose_name='output id')),
                ('data', models.BinaryField(verbose_name='test data')),
                ('logNotes', models.CharField(max_length=200, verbose_name='log notes')),
                ('testID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.test', verbose_name='test id')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputFileAttachments', models.FilePathField(path='/home/screenshots', verbose_name='output file directory')),
                ('outputId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.result', verbose_name='output id')),
            ],
        ),
    ]
