# Generated by Django 4.2.4 on 2023-09-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='reportDate',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
    ]
